PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX DMProcess:<http://www.semanticweb.org/DM/ontologies/DMProcess.owl#>
prefix MLOps:<http://www.semanticweb.org/DM/ontologies/MLOpsExp#>

INSERT DATA { 
    GRAPH <http://mlops/data> {
        
        # Experiment creation
        MLOps:Iris_Exp a DMProcess:MLOps-Experiment .
    	MLOps:Iris_Exp DMProcess:exp_name "Iris_SVM_Exp" .
        MLOps:Iris_Exp DMProcess:exp_description "Experiment applied to iris dataset" . 
		
        # Experiment Version
        MLOps:Iris_Exp_v1 a DMProcess:DM-Process .
    	MLOps:Iris_Exp DMProcess:has_version MLOps:Iris_Exp_v1 .
        
        ## Version name
    	MLOps:Iris_Exp_v1 DMProcess:version_name "Iris_SVM_Exp_v1" .

        # Read Operator
        MLOps:read_op a DMProcess:DefaultReader .
    	MLOps:Iris_Exp_v1 DMProcess:utilize MLOps:read_op .
        
        ## Read Operator Enviroment
		MLOps:Python a DMProcess:Enviroment .
        MLOps:read_op DMProcess:exec_env MLOps:Python .
		
        ## Read Operator Input
        MLOps:iris a DMProcess:DataTable . 
        MLOps:read_op DMProcess:has_specified_input MLOps:iris .
		
        ## Read Operator Output
        MLOps:IrisDataset a DMProcess:DataTable . 
        MLOps:read_op DMProcess:has_specified_output MLOps:IrisDataset .

        # Encode Operator
        MLOps:encode_op a DMProcess:ReformatData .
    	MLOps:Iris_Exp_v1 DMProcess:utilize MLOps:encode_op .
        
        ## Encode Operator Env
		MLOps:Python a DMProcess:Enviroment .
        MLOps:encode_op DMProcess:exec_env MLOps:Python .

        ## Encode Operator Input
        MLOps:IrisDataset a DMProcess:DataTable . 
        MLOps:encode_op DMProcess:has_specified_input MLOps:IrisDataset .

        ## Encode Operator Output
        MLOps:EncodedIrisDataset a DMProcess:DataTable . 
        MLOps:encode_op DMProcess:has_specified_output MLOps:EncodedIrisDataset .
		
        ## Encode Operator Parameter
        ### Encode target
        MLOps:target_param a DMProcess:Parameter . 
        MLOps:encode_op DMProcess:has_parameter MLOps:target_param .

        MLOps:target_param_value a DMProcess:DirectValue .
        
        MLOps:target_param DMProcess:parameter_name "encode_target" . 
        MLOps:target_param DMProcess:parameter_value MLOps:target_param_value .

        MLOps:target_param_value DMProcess:simple_value "class" .

        ## Encode Operator Parameter
        ### Map parameter
        MLOps:map_param a DMProcess:Parameter . 
        MLOps:encode_op DMProcess:has_parameter MLOps:map_param .

        MLOps:map_param_value a DMProcess:KeyValueCollection .
        
        MLOps:map_param DMProcess:parameter_name "map" . 
        MLOps:map_param DMProcess:parameter_value MLOps:map_param_value .


        MLOps:class_1_el a DMProcess:KeyValueElement .
        
        MLOps:map_param_value DMProcess:has_key_value_element MLOps:class_1_el .

        MLOps:iris_setosa_class a DMProcess:DirectValue . 
        
        MLOps:class_1_el DMProcess:value MLOps:iris_setosa_class .
        
        MLOps:class_1_el DMProcess:key "Iris-setosa" .

        MLOps:iris_setosa_class DMProcess:simple_value 1 .


        MLOps:class_2_el a DMProcess:KeyValueElement .
        
        MLOps:map_param_value DMProcess:has_key_value_element MLOps:class_2_el .

        MLOps:iris_versicolor_class a DMProcess:DirectValue . 
        
        MLOps:class_2_el DMProcess:value MLOps:iris_versicolor_class .
        
        MLOps:class_2_el DMProcess:key "Iris-versicolor" .

        MLOps:iris_versicolor_class DMProcess:simple_value 2 .


        MLOps:class_3_el a DMProcess:KeyValueElement .
        
        MLOps:map_param_value DMProcess:has_key_value_element MLOps:class_3_el .

        MLOps:iris_virginica_class a DMProcess:DirectValue . 
        
        MLOps:class_3_el DMProcess:value MLOps:iris_virginica_class .
        
        MLOps:class_3_el DMProcess:key "Iris-virginica" .

        MLOps:iris_virginica_class DMProcess:simple_value 3 .
        
        # Correlation Operator
		MLOps:correlation_op a DMProcess:CorrelationMatrix .
    	MLOps:Iris_Exp_v1 DMProcess:utilize MLOps:correlation_op .
        
        ## Correlation Operator Env
		MLOps:Python a DMProcess:Enviroment .
        MLOps:correlation_op DMProcess:exec_env MLOps:Python .
        
        ## Correlation Operator Input
        MLOps:EncodedIrisDataset a DMProcess:DataTable . 
        MLOps:correlation_op DMProcess:has_specified_input MLOps:EncodedIrisDataset .
        
        ## Correlation Operator Output
        MLOps:CorrelationGraph a DMProcess:Graph .
        MLOps:correlation_op DMProcess:has_specified_output MLOps:CorrelationGraph .
		
        # Split Operator
		MLOps:split_op a DMProcess:SplitData .
    	MLOps:Iris_Exp_v1 DMProcess:utilize MLOps:split_op .
        
        ## Split Operator Env
		MLOps:Python a DMProcess:Enviroment .
        MLOps:split_op DMProcess:exec_env MLOps:Python .
        
        ## Split Operator Input
		MLOps:EncodedIrisDataset a DMProcess:DataTable . 
        MLOps:split_op DMProcess:has_specified_input MLOps:EncodedIrisDataset .
        
        ## Split Operator Output
        MLOps:IrisTrain a DMProcess:DataTable .
        MLOps:split_op DMProcess:has_specified_output MLOps:IrisTrain .
        
		## Split Operator Output
		MLOps:IrisTest a DMProcess:DataTable .
        MLOps:split_op DMProcess:has_specified_output MLOps:IrisTest .
        
        ## Split Operator Parameters
        ### Split ratio parameter
		MLOps:split_ratio a DMProcess:Parameter . 
        MLOps:split_op DMProcess:has_parameter MLOps:split_ratio .

        MLOps:split_ratio_value a DMProcess:DirectValue .
        
        MLOps:split_ratio DMProcess:parameter_name "split_ratio" . 
        MLOps:split_ratio DMProcess:parameter_value MLOps:split_ratio_value .

        MLOps:split_ratio_value DMProcess:simple_value 0.25 .

        # Model Operator 
		MLOps:model_op a DMProcess:RM_Support_Vector_Machine .
    	MLOps:Iris_Exp_v1 DMProcess:utilize MLOps:model_op .
        
        ## Model Operator env
		MLOps:Python a DMProcess:Enviroment .
        MLOps:model_op DMProcess:exec_env MLOps:Python .
        
        ## Model Operator Input
		MLOps:IrisTrain a DMProcess:DataTable . 
        MLOps:model_op DMProcess:has_specified_input MLOps:IrisTrain .

		MLOps:IrisTest a DMProcess:DataTable . 
        MLOps:model_op DMProcess:has_specified_input MLOps:IrisTest .
        
        ## Model Operator Output
        MLOps:SVM_Model a DMProcess:PredictionModel .
        MLOps:model_op DMProcess:has_specified_output MLOps:SVM_Model .
        
        ## Model Operator Parameters
		### Kernel type
        MLOps:svm_kernel a DMProcess:Parameter . 
        MLOps:model_op DMProcess:has_parameter MLOps:svm_kernel .

        MLOps:svm_kernel_value a DMProcess:DirectValue .
        
        MLOps:svm_kernel DMProcess:parameter_name "kernel" . 
        MLOps:svm_kernel DMProcess:parameter_value MLOps:svm_kernel_value .

        MLOps:svm_kernel_value DMProcess:simple_value "linear" .
        
		# Eval Operator 
		MLOps:eval_op a DMProcess:ConfusionMatrix .
    	MLOps:Iris_Exp_v1 DMProcess:utilize MLOps:eval_op .
        
        ## Eval Operator env
		MLOps:Python a DMProcess:Enviroment .
        MLOps:eval_op DMProcess:exec_env MLOps:Python .
        
        ## Eval Operator inputs
		MLOps:SVM_Model a DMProcess:PredictionModel . 
        MLOps:eval_op DMProcess:has_specified_input MLOps:SVM_Model .

		MLOps:IrisTest a DMProcess:DataTable . 
        MLOps:eval_op DMProcess:has_specified_input MLOps:IrisTest .
        
        ## Eval Operator outputs
        MLOps:eval_result a DMProcess:ConfusionMatrixReport .
        MLOps:eval_op DMProcess:has_specified_output MLOps:eval_result .
        
        #iris metadata description
        
        ## TableFormat Declaration
        MLOps:Iris_TableFormat a DMProcess:TableFormat .
        MLOps:iris DMProcess:described_by MLOps:Iris_TableFormat .

        ## TableFormat Declaration
        MLOps:Iris_TableFormat a DMProcess:TableFormat .
        MLOps:IrisDataset DMProcess:described_by MLOps:Iris_TableFormat .

        ## Attribute declaration
        MLOps:iris_atr_1 a DMProcess:Attribute .
        MLOps:iris_atr_1 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_1 DMProcess:attributeName "sepal_length_in_cm" .
        
        MLOps:Iris_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_1 .
        
        ## Attribute declaration
        MLOps:iris_atr_2 a DMProcess:Attribute .
        MLOps:iris_atr_2 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_2 DMProcess:attributeName "sepal_width_in_cm" .
        
        MLOps:Iris_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_2 .

        ## Attribute declaration
        MLOps:iris_atr_3 a DMProcess:Attribute .
        MLOps:iris_atr_3 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_3 DMProcess:attributeName "petal_length_in_cm" .
        
        MLOps:Iris_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_3 .

        ## Attribute declaration
        MLOps:iris_atr_4 a DMProcess:Attribute .
        MLOps:iris_atr_4 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_4 DMProcess:attributeName "petal_width_in_cm" .
        
        MLOps:Iris_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_4 .

        ## Attribute declaration
        MLOps:iris_atr_5 a DMProcess:Attribute .
        MLOps:iris_atr_5 DMProcess:attributePossibleType DMProcess:iString .
        MLOps:iris_atr_5 DMProcess:attributeName "class" .
        
        MLOps:Iris_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_5 .

        ## TableFormat Declaration
        MLOps:Iris_Encoded_TableFormat a DMProcess:TableFormat .
        MLOps:EncodedIrisDataset DMProcess:described_by MLOps:Iris_Encoded_TableFormat .

        ## TableFormat Declaration
        MLOps:Iris_Encoded_TableFormat a DMProcess:TableFormat .
        MLOps:IrisTrain DMProcess:described_by MLOps:Iris_Encoded_TableFormat .

        ## TableFormat Declaration
        MLOps:Iris_Encoded_TableFormat a DMProcess:TableFormat .
        MLOps:IrisTest DMProcess:described_by MLOps:Iris_Encoded_TableFormat .

        ## Attribute declaration
        MLOps:iris_atr_1 a DMProcess:Attribute .
        MLOps:iris_atr_1 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_1 DMProcess:attributeName "sepal_length_in_cm" .
        
        MLOps:Iris_Encoded_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_1 .
        
        ## Attribute declaration
        MLOps:iris_atr_2 a DMProcess:Attribute .
        MLOps:iris_atr_2 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_2 DMProcess:attributeName "sepal_width_in_cm" .
        
        MLOps:Iris_Encoded_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_2 .

        ## Attribute declaration
        MLOps:iris_atr_3 a DMProcess:Attribute .
        MLOps:iris_atr_3 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_3 DMProcess:attributeName "petal_length_in_cm" .
        
        MLOps:Iris_Encoded_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_3 .

        ## Attribute declaration
        MLOps:iris_atr_4 a DMProcess:Attribute .
        MLOps:iris_atr_4 DMProcess:attributePossibleType DMProcess:32Float .
        MLOps:iris_atr_4 DMProcess:attributeName "petal_width_in_cm" .
        
        MLOps:Iris_Encoded_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_4 .

        ## Attribute declaration
        MLOps:iris_atr_6 a DMProcess:Attribute .
        MLOps:iris_atr_6 DMProcess:attributePossibleType DMProcess:32Int .
        MLOps:iris_atr_6 DMProcess:attributeName "class" .
        
        MLOps:Iris_Encoded_TableFormat  DMProcess:containsAttribute MLOps:iris_atr_6 .

    }
}