PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX DMProcess:<http://www.semanticweb.org/DM/ontologies/DMProcess.owl#>

select ?plainValue where {
    ?DirectValue DMProcess:simple_value ?plainValue .
}