PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX DMProcess:<http://www.semanticweb.org/DM/ontologies/DMProcess.owl#>

select ?directSub where {
    ?operator rdf:type ?directSub .
    FILTER NOT EXISTS { ?sub rdfs:subClassOf ?directSub . }
    FILTER ( STRSTARTS(STR(?directSub),str(DMProcess:)) )
}
