networks:
  airflow_flow-net:
    external: true
services:
  web:
    container_name: ejecutor
    image: penafieldavid471/ejecutor_scripts:v1
    networks:
    - airflow_flow-net
    ports:
    - 4001:4001
    volumes:
    - ./scripts:/root/scripts
    - ~/images:/root/images
