import { createSlice, PayloadAction } from '@reduxjs/toolkit'
import { RootState } from '../../store';
import { DatasetVersion, IDataset, MetaRecord, Preview } from '../../storetypes';


interface DatasetSliceState{
    datasets: {[key:string]:IDataset}
}

const initialState:DatasetSliceState = {
    datasets:{
        'DatasetTest': {
            name:'DatasetTest',
            versions: [
                {
                    name: 'DatasetV1',
                    tableName: 'DatasetTestV1',
                    preview: {
                        meta: [
                            {
                                dataIndex:'col1',
                                key:'col1',
                                title:'Col 1'
                            }as MetaRecord,
                            {
                                dataIndex:'col2',
                                key:'col2',
                                title:'Col 2'
                            }as MetaRecord,
                            {
                                dataIndex:'col3',
                                key:'col3',
                                title:'Col 3'
                            }as MetaRecord,
                        ],
                        records: [
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },,
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                        ]
                    }as Preview
                } as DatasetVersion,
                {
                    name: 'DatasetV2',
                    tableName: 'DatasetTestV2',
                    preview: {
                        meta: [
                            {
                                dataIndex:'col1',
                                key:'col1',
                                title:'Col 1'
                            }as MetaRecord,
                            {
                                dataIndex:'col2',
                                key:'col2',
                                title:'Col 2'
                            }as MetaRecord,
                            {
                                dataIndex:'col3',
                                key:'col3',
                                title:'Col 3'
                            }as MetaRecord,
                        ],
                        records: [
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            },
                            {
                                'col1':123,
                                'col2':123,
                                'col3':123,
                            }
                        ]
                    }as Preview
                }
            ]
        } as IDataset
    }
}

const datasetSlice = createSlice({
  name: 'datasets',
  initialState,
  reducers: {
    addVersion: (state,action: PayloadAction<{datasetKey:string,datasetVersion:DatasetVersion}>)=>{
        state.datasets[action.payload.datasetKey].versions.push(action.payload.datasetVersion)
    },
  }
});

export const {addVersion} = datasetSlice.actions

export const selectDatasets = (state: RootState) => state.datasets.datasets

export default datasetSlice.reducer